### ISSUE TITLE
Calc Clothoid

### ISSUE THREAD

**Issue by Seebbe** [SEilers/Curves#3]
Hello!
Ive been checking your code here and im quite new to calculating curves.
I need to calculate points on a clothoid on road/railway and im wondering if your code would fit my situation.
I got length, start/end coordinate and start/end radius in meter
Not quite sure what every parameter means and can be translated into
Thank you

**Comment by SEilers** [comment]
This library contains only one solver: FromPoseAndPoint, where $x_0, y_0, \theta_0, k_0, x_f, y_f$ are given.
In your problem statement $x_0, y_0, x_f, y_f, L, R_0, R_f$ are given, so you are missing the initial orientation §\theta_0$ of the curve.

If I understand your problem correcty, you need to calculate the clothoid parameter $A$, which determines how strong the curvature changes over the length of the curve. Usually the radius $R$ is expressed as curvature $k$, which is defined as the inverse of the radius: 

$k = \frac{1}{R}$ 

This way a straight line can be defined as a curve with zero curvature instead of unlimited radius, which is numerically more handy.

In a clothoid the curvature changes proportionally with its length:

$R = \frac{A^2}{L}, L > 0$

You have given, $R_f$ (the final radius), total Length $L$.
So you can calculate $A$ with:

$\sqrt\frac{R_f}{L}$ = A

Given are: $x_0, y_0, x_f, y_f, L, R_0, R_f$. 
$k_0 = \frac{1}{R_0}$ and $k_f = \frac{1}{R_f}$
You have to find $\theta_0$ to rotate your curve until its endpoints matches the given $$ 

I don't know if the problem was given to you without out the initial orientation of the curve. 
But you can also write a solver for $\theta$ by using the FromPoseAndPoint solver.
Then you iteratively change the orientation (in radian) until the final point of the interpolation ($t = 1) is close enough to your final point $x_f, y_f$. 

For this you would check intervals of $\theta$ and find the intervals with the smallest distances to your final point.
Then you subdivide this interval again and check again and so on until the distance is small enough (for examle less than a centimeter (0.01)).

Then you plug in all the values you found in the class and use the GetPoints Method to calculate the points on the curve.

Hope this helps.
